credentials:
  usernames:
    Admin:
      email: user2@example.com
      name: Admin
      password: Admin

cookie:
  expiry_days: 30
  key: some_random_key
  name: some_cookie_name

preauthorized:
  emails:
    
