credentials:
  usernames:
    ProductSupport:
      email: user1@example.com
      name: Product Support Team 
      password: Alog2024!
    Admin:
      email: user2@example.com
      name: Admin
      password: Alog2024!

cookie:
  expiry_days: 30
  key: some_random_key
  name: some_cookie_name

preauthorized:
  emails:
    - kgreenwood4@yahoo.com
